Name:		HandBrake
Version:	0.9.5
Release:	1%{?dist}
Summary:	A program to transcode DVDs and other sources to MPEG-4

Group:		Applications/Multimedia
License:	GPLv2
URL:		http://handbrake.fr/
Source0:	http://handbrake.fr/rotation.php?file=%{name}-%{version}.tar.bz2
BuildRequires:	bzip2-devel
BuildRequires:	desktop-file-utils
BuildRequires:	gcc-c++
BuildRequires:	glib2-devel
BuildRequires:	gstreamer-devel
BuildRequires:	gstreamer-plugins-base-devel
BuildRequires:	gtk2-devel
BuildRequires:	intltool
BuildRequires:	libgudev1-devel
BuildRequires:	libnotify-devel
BuildRequires:	libtool
BuildRequires:	webkitgtk-devel
BuildRequires:	yasm

# Patch from Arch Linux to fix the missing dbus/dbus-glib.h issue
# http://projects.archlinux.org/svntogit/community.git/tree/trunk/dbus-glib.patch?h=packages/handbrake
Patch0:		add_dbus-glib_to_ghb_packages.patch
# Patch from Arch Linux to fix build against libnotify 0.7.*
# http://projects.archlinux.org/svntogit/community.git/tree/trunk/libnotify-0.7.patch?h=packages/handbrake
Patch1:		fix_build_with_libnotify_0.7.patch

# Nothing should be downloaded during the build
# The following was generated by this command:
#   COUNT=1 && for i in *; do echo -e "Source${COUNT}:\t$(grep url ${i}/module.defs | awk -F'= ' '{print $2}')"; let COUNT++; done; unset COUNT
Source1:	http://download.m0k.org/handbrake/contrib/a52dec-0.7.4.tar.gz
Source2:	http://download.handbrake.fr/handbrake/contrib/bzip2-1.0.6.tar.gz
Source3:	http://download.m0k.org/handbrake/contrib/faac-1.28.tar.gz
Source4:	http://download.m0k.org/handbrake/contrib/faad2-2.7.tar.gz
Source5:	http://download.m0k.org/handbrake/contrib/ffmpeg-r25689.tar.bz2
Source6:	http://download.m0k.org/handbrake/contrib/fontconfig-2.8.0.tar.gz
Source7:	http://download.m0k.org/handbrake/contrib/freetype-2.3.9.tar.gz
Source8:	http://download.m0k.org/handbrake/contrib/lame-3.98.tar.gz
Source9:	http://download.m0k.org/handbrake/contrib/libass-0.9.9.tar.bz2
Source10:	http://download.m0k.org/handbrake/contrib/libbluray-0.0.1-pre-16-g1aab213.tar.gz
Source11:	http://download.m0k.org/handbrake/contrib/libdca-r81-strapped.tar.gz
Source12:	http://download.m0k.org/handbrake/contrib/libdvdnav-svn1168.tar.gz
Source13:	http://download.m0k.org/handbrake/contrib/libdvdread-svn1168.tar.gz
Source14:	http://download.m0k.org/handbrake/contrib/libiconv-1.13.tar.bz2
Source15:	http://download.m0k.org/handbrake/contrib/libmkv-0.6.4.1-0-ga80e593.tar.bz2
Source16:	http://download.m0k.org/handbrake/contrib/libogg-1.1.3.tar.gz
Source17:	http://download.m0k.org/handbrake/contrib/libsamplerate-0.1.4.tar.gz
Source18:	http://download.m0k.org/handbrake/contrib/libtheora-1.1.0.tar.bz2
Source19:	http://download.m0k.org/handbrake/contrib/libvorbis-aotuv_b5.tar.gz
Source20:	http://download.m0k.org/handbrake/contrib/libxml2-2.7.7.tar.gz
Source21:	http://download.m0k.org/handbrake/contrib/mp4v2-trunk-r355.tar.bz2
Source22:	http://download.m0k.org/handbrake/contrib/mpeg2dec-0.5.1.tar.gz
Source23:	http://download.m0k.org/handbrake/contrib/pthreads-w32-cvs20100909.tar.bz2
Source24:	http://download.handbrake.fr/handbrake/contrib/x264-r1834-a51816a.tar.gz
Source25:	http://download.m0k.org/handbrake/contrib/zlib-1.2.3.tar.gz



%description
HandBrake is an open-source, GPL-licensed, multi-platform, multi-threaded 
transcoder, available for MacOS X, Linux and Windows.


%package gtk
Summary:	A program to transcode DVDs and other sources to MPEG-4
Group:		Applications/Multimedia


%package cli
Summary:	A program to transcode DVDs and other sources to MPEG-4
Group:		Applications/Multimedia


%description gtk
HandBrake is an open-source, GPL-licensed, multi-platform, multi-threaded 
transcoder, available for MacOS X, Linux and Windows.


%description cli
HandBrake is an open-source, GPL-licensed, multi-platform, multi-threaded 
transcoder, available for MacOS X, Linux and Windows.


%prep
%setup -q
%patch0 -p1
%patch1 -p1

# Convert files to UTF-8
iconv -f ISO8859-1 -t UTF-8 < CREDITS > CREDITS.utf8
cp CREDITS.utf8 CREDITS
iconv -f ISO8859-1 -t UTF-8 < THANKS > THANKS.utf8
cp THANKS.utf8 THANKS


%build
# Symlink the source files so they won't be downloaded during the build
mkdir -p download/
ln -s %{SOURCE1} download/
ln -s %{SOURCE2} download/
ln -s %{SOURCE3} download/
ln -s %{SOURCE4} download/
ln -s %{SOURCE5} download/
ln -s %{SOURCE6} download/
ln -s %{SOURCE7} download/
ln -s %{SOURCE8} download/
ln -s %{SOURCE9} download/
ln -s %{SOURCE10} download/
ln -s %{SOURCE11} download/
ln -s %{SOURCE12} download/
ln -s %{SOURCE13} download/
ln -s %{SOURCE14} download/
ln -s %{SOURCE15} download/
ln -s %{SOURCE16} download/
ln -s %{SOURCE17} download/
ln -s %{SOURCE18} download/
ln -s %{SOURCE19} download/
ln -s %{SOURCE20} download/
ln -s %{SOURCE21} download/
ln -s %{SOURCE22} download/
ln -s %{SOURCE23} download/
ln -s %{SOURCE24} download/
ln -s %{SOURCE25} download/

# This is not a traditional GNU autotools configure file
./configure --disable-gtk-update-checks --debug=max --prefix=%{_prefix}

# Parallel build fails
#make %{?_smp_mflags} -C build
make -j1 -C build


%install
make -C build DESTDIR=$RPM_BUILD_ROOT install

# Remove deprecated "Encoding" line from the desktop file
sed -i '/Encoding/d' $RPM_BUILD_ROOT%{_datadir}/applications/ghb.desktop

# Validate desktop file
desktop-file-validate $RPM_BUILD_ROOT%{_datadir}/applications/ghb.desktop

# Remove icon cache file as it is generated during installation
#rm -v $RPM_BUILD_ROOT%{_datadir}/icons/hicolor/icon-theme.cache


%clean
rm -rf %{buildroot}


%post gtk
/bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null || :
if [ -x /usr/bin/gtk-update-icon-cache ]; then
  /usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
fi


%postun gtk
/bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null || :
if [ -x /usr/bin/gtk-update-icon-cache ]; then
  /usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
fi


%files gtk
%defattr(-,root,root,-)
%doc NEWS AUTHORS CREDITS THANKS COPYING
%{_datadir}/icons/hicolor/128x128/apps/hb-icon.png
%{_datadir}/applications/ghb.desktop
%{_bindir}/ghb


%files cli
%defattr(-,root,root,-)
%doc NEWS AUTHORS CREDITS THANKS COPYING
%{_bindir}/HandBrakeCLI


%changelog
* Sun Jan 15 2012 Xiao-Long Chen <chenxiaolong@cxl.epac.to> - 0.9.5-1
- Upstream release
- Based off of upstream example spec file


