Name:		HandBrake
Version:	0.9.6
Release:	1%{?dist}
Summary:	A program to transcode DVDs and other sources to MPEG-4

Group:		Applications/Multimedia
License:	GPLv2
URL:		http://handbrake.fr/
Source0:	http://handbrake.fr/rotation.php?file=%{name}-%{version}.tar.bz2
BuildRequires:	bzip2-devel
BuildRequires:	desktop-file-utils
BuildRequires:	fribidi-devel
BuildRequires:	gcc-c++
BuildRequires:	glib2-devel
BuildRequires:	gstreamer-devel
BuildRequires:	gstreamer-plugins-base-devel
BuildRequires:	gtk2-devel
BuildRequires:	intltool
BuildRequires:	libgudev1-devel
BuildRequires:	libnotify-devel
BuildRequires:	libtool
BuildRequires:	webkitgtk-devel
BuildRequires:	yasm

# Nothing should be downloaded during the build
# The following was generated by this command:
#   COUNT=1 && for i in *; do echo -e "Source${COUNT}:\t$(grep url ${i}/module.defs | awk -F'= ' '{print $2}')"; let COUNT++; done; unset COUNT
Source1:	http://download.handbrake.fr/handbrake/contrib/a52dec-0.7.4.tar.gz
Source2:	http://download.handbrake.fr/handbrake/contrib/bzip2-1.0.6.tar.gz
Source3:	http://download.handbrake.fr/handbrake/contrib/faac-1.28.tar.gz
Source4:	http://download.handbrake.fr/handbrake/contrib/faad2-2.7.tar.gz
Source5:	http://download.handbrake.fr/handbrake/contrib/ffmpeg-v0.7-1696-gcae4f4b.tar.bz2
Source6:	http://download.handbrake.fr/handbrake/contrib/fontconfig-2.8.0.tar.gz
Source7:	http://download.handbrake.fr/handbrake/contrib/freetype-2.4.7.tar.bz2
Source8:	http://download.handbrake.fr/handbrake/contrib/fribidi-0.19.2.tar.gz
Source9:	http://download.handbrake.fr/handbrake/contrib/lame-3.98.tar.gz
Source10:	http://download.handbrake.fr/handbrake/contrib/libass-0.10.0-1.tar.gz
Source11:	http://download.handbrake.fr/handbrake/contrib/libbluray-0.0.1-pre-213-ga869da8.tar.gz
Source12:	http://download.handbrake.fr/handbrake/contrib/libdca-r81-strapped.tar.gz
Source13:	http://download.handbrake.fr/handbrake/contrib/libdvdnav-svn1168.tar.gz
Source14:	http://download.handbrake.fr/handbrake/contrib/libdvdread-svn1168.tar.gz
Source15:	http://download.handbrake.fr/handbrake/contrib/libiconv-1.13.tar.bz2
Source16:	http://download.handbrake.fr/handbrake/contrib/libmkv-0.6.5-0-g82075ae.tar.gz
Source17:	http://download.handbrake.fr/handbrake/contrib/libogg-1.3.0.tar.gz
Source18:	http://download.handbrake.fr/handbrake/contrib/libsamplerate-0.1.4.tar.gz
Source19:	http://download.handbrake.fr/handbrake/contrib/libtheora-1.1.0.tar.bz2
Source20:	http://download.handbrake.fr/handbrake/contrib/libvorbis-aotuv_b6.03.tar.bz2
Source21:	http://download.handbrake.fr/handbrake/contrib/libxml2-2.7.7.tar.gz
Source22:	http://download.handbrake.fr/handbrake/contrib/mp4v2-trunk-r355.tar.bz2
Source23:	http://download.handbrake.fr/handbrake/contrib/mpeg2dec-0.5.1.tar.gz
Source24:	http://download.handbrake.fr/handbrake/contrib/pthreads-w32-cvs20100909.tar.bz2
Source25:	http://download.handbrake.fr/handbrake/contrib/x264-r2146-bcd41db.tar.gz
Source26:	http://download.handbrake.fr/handbrake/contrib/yasm-1.1.0.tar.gz
Source27:	http://download.handbrake.fr/handbrake/contrib/zlib-1.2.3.tar.gz


%description
HandBrake is an open-source, GPL-licensed, multi-platform, multi-threaded 
transcoder, available for MacOS X, Linux and Windows.


%package gtk
Summary:	A program to transcode DVDs and other sources to MPEG-4
Group:		Applications/Multimedia


%package cli
Summary:	A program to transcode DVDs and other sources to MPEG-4
Group:		Applications/Multimedia


%description gtk
HandBrake is an open-source, GPL-licensed, multi-platform, multi-threaded 
transcoder, available for MacOS X, Linux and Windows.


%description cli
HandBrake is an open-source, GPL-licensed, multi-platform, multi-threaded 
transcoder, available for MacOS X, Linux and Windows.


%prep
%setup -q

# Convert files to UTF-8
iconv -f ISO8859-1 -t UTF-8 < CREDITS > CREDITS.utf8
cp CREDITS.utf8 CREDITS
iconv -f ISO8859-1 -t UTF-8 < THANKS > THANKS.utf8
cp THANKS.utf8 THANKS


%build
# Symlink the source files so they won't be downloaded during the build
mkdir -p download/
ln -s %{SOURCE1} download/
ln -s %{SOURCE2} download/
ln -s %{SOURCE3} download/
ln -s %{SOURCE4} download/
ln -s %{SOURCE5} download/
ln -s %{SOURCE6} download/
ln -s %{SOURCE7} download/
ln -s %{SOURCE8} download/
ln -s %{SOURCE9} download/
ln -s %{SOURCE10} download/
ln -s %{SOURCE11} download/
ln -s %{SOURCE12} download/
ln -s %{SOURCE13} download/
ln -s %{SOURCE14} download/
ln -s %{SOURCE15} download/
ln -s %{SOURCE16} download/
ln -s %{SOURCE17} download/
ln -s %{SOURCE18} download/
ln -s %{SOURCE19} download/
ln -s %{SOURCE20} download/
ln -s %{SOURCE21} download/
ln -s %{SOURCE22} download/
ln -s %{SOURCE23} download/
ln -s %{SOURCE24} download/
ln -s %{SOURCE25} download/
ln -s %{SOURCE26} download/
ln -s %{SOURCE27} download/

# This is not a traditional GNU autotools configure file
./configure --disable-gtk-update-checks --debug=max --prefix=%{_prefix}

make %{?_smp_mflags} -C build


%install
# Install and strip since /usr/lib/rpm/find-debuginfo.sh can't handle the
# .debug_macro debugging section yet.
make -C build DESTDIR=$RPM_BUILD_ROOT install-strip

# Remove deprecated "Encoding" line from the desktop file
sed -i '/Encoding/d' $RPM_BUILD_ROOT%{_datadir}/applications/ghb.desktop

# Validate desktop file
desktop-file-validate $RPM_BUILD_ROOT%{_datadir}/applications/ghb.desktop


%clean
rm -rf %{buildroot}


%post gtk
/bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null || :
if [ -x /usr/bin/gtk-update-icon-cache ]; then
  /usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
fi


%postun gtk
/bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null || :
if [ -x /usr/bin/gtk-update-icon-cache ]; then
  /usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
fi


%files gtk
%defattr(-,root,root,-)
%doc NEWS AUTHORS CREDITS THANKS COPYING
%{_datadir}/icons/hicolor/128x128/apps/hb-icon.png
%{_datadir}/applications/ghb.desktop
%{_bindir}/ghb


%files cli
%defattr(-,root,root,-)
%doc NEWS AUTHORS CREDITS THANKS COPYING
%{_bindir}/HandBrakeCLI


%changelog
* Wed Feb 29 2012 Xiao-Long Chen <chenxiaolong@cxl.epac.to> - 0.9.6-1
- Leap day
- Update to version 0.9.6

* Sun Jan 15 2012 Xiao-Long Chen <chenxiaolong@cxl.epac.to> - 0.9.5-1
- Upstream release
- Based off of upstream example spec file
